### ISSUE TITLE
Feature Request: Automatic Hydrate

### ISSUE THREAD

**Issue by sarfraznawaz2005** [esensi/model#39]
Thanks for the great useful traits :smile: 

Is there automatic hydrate feature available? For example instead of doing:

    $user           = new User;
    $user->name     = Input::get('name');
    $user->email    = Input::get('email');
    $user->password = Hash::make(Input::get('password'));
    $user->save();

I would just like to do:

    $user = new User;
    $user->save();

That would automatically purge things not specified in `fillable` array. 

This is the only feature that has still kept me using Ardent ([which has this feature](https://github.com/laravel-ardent/ardent#automatically-hydrate-ardent-entities)) but I would love to use this package but not sure if it already has this feature.

Thanks

**Comment by dalabarge** [comment]
You can:

```php
$user = new User;
$user->fill(request()->all());
$user->save();
```

or even

```php
$user = new User(request()->all());
$user->save();
```

Which is more explicit and therefore more developer preferred choice for hydrating a model from a request. If we were to add auto-hydration it would be via a developer exposed public API method such as a static factory method:

```php
$user = User::autofill()->save();
```

And we'd have to make sure that the `Request` object could still be passed into the `autofill()` as an argument so that the code base remains SOLID.

I understand that for many apps where requests are mapped to models and persisted that this is a deliberate choice for developer convenience. In our use (including prior experience with Ardent which was why we build this package), it actually leads to a larger anti-pattern of convenience and coupling over explicitness and decoupling which SRP promotes. If it is the concern of a model to be saved to the database, it is the concern of the code that calls save to also fill the model with the request. Only when that task is repetitious enough that a convenience method like the `autofill()` method would be should it be introduced – but again then it would be a developer choice (explicitness) instead of a default – and therefore potentially breaking – unintended behavior.

So with that said, if you want to submit a PR for `AutoFillableTrait` which adds the `autofill(Request $request = null)` static factory method and associated unit tests, I'd add it as an optional extra trait for those who want to utilize this convenience pattern.
